# Generated by Django 4.1.4 on 2022-12-19 22:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favourites',
            unique_together={('user', 'project')},
        ),
    ]
